proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import path,include

# from django.conf import settings
# from django.conf.urls.static import static

urlpatterns = [
    path('',include('web.urls')),
    path('paypal/', include("paypal.standard.ipn.urls")),
    path('admin/', admin.site.urls),
] #+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proyecto/web/urls.py
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index,name='index'),
    path('shop/<int:id>', views.shop,name='shop'),
    path('categoria/<int:categoria_id>', views.productos_por_categoria,name='categoria'),
    path('marca/<int:marca_id>', views.productos_por_marca,name='marca'),
    path('buscar', views.productos_por_nombre, name='buscar'),
    path('producto/<int:producto_id>',views.producto,name='producto'),
    path('carrito', views.carrito , name='carrito'),
    path('carrito/add/<int:producto_id>',views.agregar_carrito, name='carritoadd'),
    path('carrito/del/<int:producto_id>',views.eliminar_carrito,name='carritodel'),
    path('carritoclear', views.limpiar_carrito,name='carritoclear'),
    path('usuario/add',views.crear_usuario,name='usuarioadd'),
    path('cuenta', views.cuenta_usuario,name='cuenta'),
    path('login',views.login_usuario,name='usuariologin'),
    path('logout',views.logout_usuario,name='usuariologout'),
    path('cliente/update',views.actualizar_cliente,name='clienteupdate'),
    path('factura',views.confirmar_factura,name='factura'),
    path('registrarpedido',views.registrar_pedido,name='registrarpedido'),
    path('pedidopagado', views.pedido_pagado,name='pedidopagado'),
    path('contactanos', views.contactanos,name='contactanos'),
    path('about', views.sobre_nosotros,name='about'),
    path('galeria', views.mi_galeria,name='galeria'),
    path('senddata',views.correo,name='senddata'),
    path('actualizar_cantidad/', views.actualizar_cantidad, name='actualizar_cantidad'),
]

proyecto/web/templates/includes/footer.html
<div class="container-fluid blog-sb-widgets page-styling site-footer">
    <div class="row">
        <div class="col-sm-12 col-md-4 widget align-center-tablet f-logo-wrap">
            <a href="index.html" class="f-logo">
                <img src="" alt="">
            </a>
            <button class="btn callback">Contáctanos</button>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-2 align-center-mobile widget">
            <h3 class="widgettitle">Compania</h3>
            <ul class="menu">
                <li>
                    <a href="{% url 'web:index' %}">Página principal</a>
                </li>
                <li>
                    <a href="{% url 'web:about' %}">Nosotros</a>
                </li>
                <li>
                    <a href="{% url 'web:contactanos' %}">Contáctanos</a>
                </li>
            </ul>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-2 align-center-mobile widget">
            <h3 class="widgettitle">Tienda</h3>
            <ul class="menu">
                <li>
                    <a href="{% url 'web:shop' 1 %}">Collares</a>
                </li>
                <li>
                    <a href="{% url 'web:shop' 1 %}">Pulceras</a>
                </li>
                <li>
                    <a href="{% url 'web:shop' 1 %}">Anillos</a>
                </li>
            </ul>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-2 align-center-mobile widget">
            <h3 class="widgettitle">Cuenta</h3>
            <ul class="menu">
                <li>
                    <a href="{% url 'web:galeria' %}">Mi Galeria</a>
                </li>
                <li>
                    <a href="{% url 'web:carrito' %}">Carrito</a>
                </li>
                <li>
                    <a href="{% url 'web:usuariologin' %}">Mi Cuenta</a>
                </li>
            </ul>
        </div>
    </div>
</div>

proyecto/web/templates/includes/header.html
{% load static %}
<div class="site-header">

    <p class="h-logo">
        <a href="/"><img src="{% static 'img/logo_encantos_finos.png' %}" alt="MultiShop" style="width: 50%;" /></a>
    </p><!--
No Space
--><div class="h-shop">

    <form method="post" action="{% url 'web:buscar' %}" class="h-search" id="h-search">
        {% csrf_token %}
        <input type="text" name="nombre" placeholder="Buscar...">
        <button type="submit"><i class="ion-search"></i></button>
    </form>

    <ul class="h-shop-links">
        <li class="h-search-btn" id="h-search-btn"><i class="ion-search"></i></li>
        <li class="h-shop-icon h-profile">
            <a href="{% url 'web:cuenta' %}" title="Mi cuenta">
                <i class="ion-android-person"></i>
            </a>
            <ul class="h-profile-links">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'web:usuariologout' %}">Cerrar sesion</a></li>
                {% else %}
                    <li><a href="{% url 'web:usuariologin' %}">Acceder / Registrarse</a></li>
                {% endif %}
                    <li><a href="{% url 'web:carrito' %}">Carrito de compras</a></li>
            </ul>
        </li>

        <li class="h-cart">
            <a class="cart-contents" href="{% url 'web:carrito' %}">
                <p class="h-cart-icon">
                    <i class="ion-android-cart"></i>
                    <span>3</span>
                </p>
                <p class="h-cart-total">$510.00</p>
            </a>
        </li>

        <li class="h-menu-btn" id="h-menu-btn">
            <i class="ion-navicon"></i> Menu
        </li>
    </ul>
</div><!--
No Space
--><div class="mainmenu">

    <nav id="h-menu" class="h-menu">
        <ul>
            <li class="menu-item-has-children">
                <a href="{% url 'web:index' %}">Principal</a>
            </li>
            <li class="menu-item-has-children active">
                <a href="{% url 'web:shop' 1 %}">Tienda</a>
            </li>
            <li>
                <a href="{% url 'web:contactanos' %}">Contáctanos</a>
            </li>
            <li class="menu-item-has-children">
                <a href="{% url 'web:about' %}">Nosotros</a>
            </li>
        </ul>
    </nav>

</div><!--
No Space
--></div>

proyecto/web/templates/includes/modals.html
<div class="form-validate modal-form" id="modal-form">
    <form action="#" method="POST" class="form-validate">
        <h4>Contact Us</h4>
        <input type="text" placeholder="Your name" data-required="text" name="name">
        <input type="text" placeholder="Your phone" data-required="text" name="phone">
        <input type="text" placeholder="Your email" data-required="text" data-required-email="email" name="email">
        <input class="btn1" type="submit" value="Send">
    </form>
</div>
<div class="cont maincont quick-view-modal">
    <article>
        <div class="prod">
            <div class="prod-slider-wrap prod-slider-shown">
                <div class="flexslider prod-slider" id="prod-slider">
                    <ul class="slides">
                        <li>
                            <a data-fancybox-group="prod" class="fancy-img" href="http://placehold.it/1000x1000">
                                <img src="http://placehold.it/550x550" alt="">
                            </a>
                        </li>
                        <li>
                            <a data-fancybox-group="prod" class="fancy-img" href="http://placehold.it/1000x1000">
                                <img src="http://placehold.it/550x550" alt="">
                            </a>
                        </li>
                        <li>
                            <a data-fancybox-group="prod" class="fancy-img" href="http://placehold.it/1000x1000">
                                <img  src="http://placehold.it/550x550" alt="">
                            </a>
                        </li>
                    </ul>
                    <div class="prod-slider-count"><p><span class="count-cur">1</span> / <span class="count-all">3</span></p><p class="hover-label prod-slider-zoom"><i class="icon ion-search"></i><span>Zoom In</span></p></div>
                </div>
                <div class="flexslider prod-thumbs" id="prod-thumbs">
                    <ul class="slides">
                        <li>
                            <img src="http://placehold.it/550x550" alt="">
                        </li>
                        <li>
                            <img src="http://placehold.it/550x550" alt="">
                        </li>
                        <li>
                            <img src="http://placehold.it/550x550" alt="">
                        </li>
                    </ul>
                </div>
            </div>
            <div class="prod-cont">
                <div class="prod-rating-wrap">
                    <p data-rating="4" class="prod-rating">
                        <i class="rating-ico" title="1"></i><i class="rating-ico" title="2"></i><i class="rating-ico" title="3"></i><i class="rating-ico" title="4"></i><i class="rating-ico" title="5"></i>
                    </p>
                    <p class="prod-rating-count">7</p>
                </div>
                <p class="prod-categs"><a href="#">Lighting</a>, <a href="#">Tools</a></p>
                <h2>Belt Sanders</h2>
                <p class="prod-price">$25.00</p>
                <p class="stock in-stock">7 in stock</p>
                <p class="prod-excerpt">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget...</p>
                <div class="prod-add">
                    <button type="submit"
                            class="button"><i class="icon ion-android-cart"></i> Add to cart
                    </button>
                    <p class="qnt-wrap prod-li-qnt">
                        <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                        <input type="text" value="1">
                        <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                    </p>
                    <div class="prod-li-favorites">
                        <a href="wishlist.html" class="hover-label add_to_wishlist"><i class="icon ion-heart"></i><span>Add to Wishlist</span></a>
                    </div>
                    <p class="prod-li-compare">
                        <a href="compare.html" class="hover-label prod-li-compare-btn"><span>Compare</span><i class="icon ion-arrow-swap"></i></a>
                    </p>
                </div>
            </div>
        </div>
    </article>
</div>

proyecto/web/templates/includes/navBar.html
<div class="container-fluid page-styling site-header-before">
    <div class="row">
        <div class="col-lg-4">
            <ul class="links_list links_list-align-left align-center-desktop topbar-social">
                <li>
                    <p class="links_list-value">
                        <a href="http://facebook.com" target="_blank" rel="nofollow">
                            <i class="fa fa-facebook"></i>
                        </a>
                    </p>
                </li>
                <li>
                    <p class="links_list-value">
                        <a href="mailto:email@email.com" target="_blank" rel="nofollow">
                            <i class="fa fa-paper-plane"></i>
                        </a>
                    </p>
                </li>
                <li>
                    <p class="links_list-value">
                        <a href="http://instagram.com" target="_blank" rel="nofollow">
                            <i class="fa fa-instagram"></i>
                        </a>
                    </p>
                </li>
            </ul>
        </div>
        <div class="col-lg-8">
            <ul class="links_list links_list-align-right align-center-desktop topbar-contacts">
                <li>
                    <p class="links_list-label">
                        Contáctanos
                    </p>
                    <p class="links_list-value">
                        <a href="mailto:support@email.com">encantos.finos@gmail.com</a>
                    </p>
                </li>
                <li>
                    <p class="links_list-label">
                        Celular
                    </p>
                    <p class="links_list-value">
                        <a href="tel:907937408">907937408</a>
                    </p>
                </li>
            </ul>
        </div>
    </div>
</div>