proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import path,include

# from django.conf import settings
# from django.conf.urls.static import static

urlpatterns = [
    path('',include('web.urls')),
    path('paypal/', include("paypal.standard.ipn.urls")),
    path('admin/', admin.site.urls),
] #+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proyecto/web/urls.py
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index,name='index'),
    path('shop/<int:id>', views.shop,name='shop'),
    path('categoria/<int:categoria_id>', views.productos_por_categoria,name='categoria'),
    path('marca/<int:marca_id>', views.productos_por_marca,name='marca'),
    path('buscar', views.productos_por_nombre, name='buscar'),
    path('producto/<int:producto_id>',views.producto,name='producto'),
    path('carrito', views.carrito , name='carrito'),
    path('carrito/add/<int:producto_id>',views.agregar_carrito, name='carritoadd'),
    path('carrito/del/<int:producto_id>',views.eliminar_carrito,name='carritodel'),
    path('carritoclear', views.limpiar_carrito,name='carritoclear'),
    path('usuario/add',views.crear_usuario,name='usuarioadd'),
    path('cuenta', views.cuenta_usuario,name='cuenta'),
    path('login',views.login_usuario,name='usuariologin'),
    path('logout',views.logout_usuario,name='usuariologout'),
    path('cliente/update',views.actualizar_cliente,name='clienteupdate'),
    path('factura',views.confirmar_factura,name='factura'),
    path('registrarpedido',views.registrar_pedido,name='registrarpedido'),
    path('pedidopagado', views.pedido_pagado,name='pedidopagado'),
    path('contactanos', views.contactanos,name='contactanos'),
    path('about', views.sobre_nosotros,name='about'),
    path('galeria', views.mi_galeria,name='galeria'),
    path('senddata',views.correo,name='senddata'),
    path('actualizar_cantidad/', views.actualizar_cantidad, name='actualizar_cantidad'),
]

proyecto/web/models.py
from django.db import models

from cloudinary.models import CloudinaryField

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'tbl_categoria'
        
    def __str__(self):
        return self.nombre
    
class Marca(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'tbl_marca'
        
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    PAIS = 'Perú'
    SEXO_CHOICES = {
        ('h' , 'men'),
        ('m' , 'women'),
        ('c' , 'children')
    }
    MATERIAL_CHOICES = {
        ('o' , 'oro'),
        ('p' , 'plata'),
        ('c' , 'cobre')
    }

    categoria = models.ForeignKey(Categoria,on_delete=models.RESTRICT)
    marca = models.ForeignKey(Marca,on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=254)
    descripcion = models.TextField(null=True)
    precio = models.DecimalField(max_digits=5,decimal_places=2)
    imagen = CloudinaryField('image',default='')
    sexo = models.CharField(max_length=1,default='m',choices=SEXO_CHOICES)
    dimensiones = models.CharField(max_length=100, default="30 x 10 cm")
    cantidad = models.IntegerField(default=0)
    peso = models.DecimalField(max_digits=5,decimal_places=2)
    pais = models.CharField(max_length=100, default=PAIS, editable=False)
    material = models.CharField(max_length=1,default='o',choices=MATERIAL_CHOICES)
    
    class Meta:
        db_table = 'tbl_producto'
        
    def __str__(self):
        return self.nombre  

from django.contrib.auth.models import User   

class Cliente(models.Model):
    usuario = models.OneToOneField(User,on_delete=models.RESTRICT)
    dni = models.CharField(max_length=8)
    telefono = models.CharField(max_length=50)
    fecha_nacimiento = models.DateField(null= True)
    direccion = models.TextField()

    class Meta:
        db_table = 'tbl_cliente'

    def __str__(self):
        return self.dni   

class Factura(models.Model):
    ESTADO_CHOICES = {
        ('s' , 'SOLICITADO'),
        ('p' , 'PAGADO')
    }
    cliente = models.ForeignKey(Cliente,on_delete=models.RESTRICT)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    monto_total = models.DecimalField(max_digits=5,decimal_places=2,default=0)
    direccion_envio = models.TextField(null=True) 
    estado = models.CharField(max_length=1,default='s',choices=ESTADO_CHOICES)
    nro_pedido = models.CharField(max_length=20,null=True)
    
    class Meta:
        db_table = 'tbl_factura'
    
    def __str__(self):
        return self.nro_pedido

class FacturaDetalle(models.Model):
    factura = models.ForeignKey(Factura,on_delete=models.RESTRICT)
    producto = models.ForeignKey(Producto,on_delete=models.RESTRICT)
    cantidad = models.IntegerField(default=1)
    precio = models.DecimalField(max_digits=5,decimal_places=2)
    subtotal = models.DecimalField(max_digits=5,decimal_places=2)

    class Meta:
        db_table = 'tbl_factura_detalle'

    def __str__(self):
        return self.producto.nombre

proyecto/web/templates/carrito.html
{% extends 'layout.html' %}
{% block content %}
<div class="cont maincont carrito">
    <h1 class="maincont-ttl">Carrito</h1>
    <div class="page-styling">
        <div class="woocommerce prod-litems section-list">
            {% for key,value in request.session.cart.items %}
            <article class="prod-li sectls">
                <div class="prod-li-inner">
                    <a href="product.html" class="prod-li-img">
                        <img src="{{value.imagen}}" alt="">
                    </a>
                    <div class="prod-li-cont">
                        <div class="prod-li-ttl-wrap">
                            <p>
                                <a href="#">{{value.categoria}}</a>
                            </p>
                            <h3><a href="product.html">{{value.nombre}}</a></h3>
                        </div>
                        <div class="prod-li-prices">
                            <div class="prod-li-price-wrap">
                                <p>Price</p>
                                <p class="prod-li-price">${{value.precio}}</p>
                            </div>
                            <div class="prod-li-qnt-wrap">
                                <p class="qnt-wrap prod-li-qnt">
                                    <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                    <input type="text" value="{{value.cantidad}}" data-product-id="{{value.producto_id}}">
                                    <a href="#" class="qnt-minus prod-li-minus"><i
                                            class="icon ion-arrow-down-b"></i></a>
                                </p>
                            </div>
                            <div class="prod-li-total-wrap">
                                <p>Subtotal</p>
                                <p class="prod-li-total">${{value.subtotal}}</p>
                            </div>
                            <div class="prod-li-total-wrap">
                                <p class="prod-li-add">
                                    <a href="{% url 'web:carritodel' value.producto_id %}"
                                        class="button hover-label prod-addbtn"><i class="icon ion-close-round"></i></a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </article>
            {% endfor %}
        </div>
        <div class="cart-actions">
            <div class="coupon">
                <input type="text" placeholder="Coupon code">
                <input type="submit" class="button" value="Apply">
            </div>
            <div class="cart-collaterals">
                <a href="{% url 'web:carritoclear' %}" class="checkout-button button">Limpiar carrito</a>
                <a href="{% url 'web:factura' %}" class="checkout-button button">Registar pedido</a>
                <div class="order-total">
                    <p class="cart-totals-ttl">Total</p>
                    <p class="cart-totals-val">{{request.session.total}}</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

proyecto/web/templates/cuenta.html
{% extends 'layout.html' %}
{% block content %}
<div class="cont maincont">
    <h1 class="maincont-ttl">Bienvenido {{user.username}}</h1>
    <h2>{{mensaje}}</h2>
    <article class="page-cont">
        <div class="page-styling">

            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Datos del cliente</h2>
                    <form method="post" class="login" action="{% url 'web:clienteupdate' %}">
                        {% csrf_token %}
                        {{form}}
                        <p class="auth-submit">
                            <input type="submit" value="Actualizar datos">
                        </p>
                    </form>
                </div>
            </div>

        </div>
    </article>
</div>
{% endblock %}

proyecto/web/templates/index.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
<div id="page" class="site">
    <div id="content" class="site-content">
        <div id="primary" class="content-area width-full">
            <main id="main" class="site-main">
                <div class="maincont page-styling page-full">

                    <div class="heroblock">
                        <div class="page-styling row-wrap-full contacts-page-map" style="margin-top: 20px;">
                            <video autoplay muted loop width="100%" allowfullscreen>
                                <source
                                src="https://www.dropbox.com/scl/fi/s8ca3cdrs77y5n856x7px/joyeria.mp4?rlkey=uhfs5b6favjb6sp53qxd8ulk1&dl=1"
                                type="video/mp4">
                            </video>
                        </div>
                        <p class="heroblock-subttl"><a href="{% url 'web:shop' 1 %}">Tienda</a></p>
                    </div>
                    <h1 class="categorias">Categorias</h1>
                    <div class="row prod-items prod-items-2">
                        <article class="cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6 sectgl-item">
                            <div class="sectgl prod-i">
                                <div class="prod-i-top">
                                    <a class="prod-i-img" href="{% url 'web:categoria' 2 %}">
                                        <img src="https://i.postimg.cc/YqQTN8t2/Pulseras.jpg" alt="">
                                    </a>
                                    <h2 class="prod-i-ttl">Pulseras</h2>
                                </div>
                            </div>
                        </article>      
                        <article class="cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6 sectgl-item">
                            <div class="sectgl prod-i">
                                <div class="prod-i-top">
                                    <a class="prod-i-img" href="{% url 'web:categoria' 4 %}">
                                        <img src="https://i.postimg.cc/1zRx36hm/Anillos.jpg" alt="">
                                    </a>
                                    <h2 class="prod-i-ttl">Anillo</h2>
                                </div>
                            </div>
                        </article>  
                        <article class="cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6 sectgl-item">
                            <div class="sectgl prod-i">
                                <div class="prod-i-top">
                                    <a class="prod-i-img" href="{% url 'web:categoria' 1 %}">
                                        <img src="https://i.postimg.cc/JngSx2y0/Collares.jpg" alt="">
                                    </a>
                                    <h2 class="prod-i-ttl">Collares</h2>
                                </div>
                            </div>
                        </article>  
                        <article class="cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6 sectgl-item">
                            <div class="sectgl prod-i">
                                <div class="prod-i-top">
                                    <a class="prod-i-img" href="{% url 'web:categoria' 5 %}">
                                        <img src="https://i.postimg.cc/SR6V9TCw/Reloj.jpg" alt="">
                                    </a>
                                    <h2 class="prod-i-ttl">Relojes</h2>
                                </div>
                            </div>
                        </article>  
                        <article class="cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6 sectgl-item">
                            <div class="sectgl prod-i">
                                <div class="prod-i-top">
                                    <a class="prod-i-img" href="{% url 'web:categoria' 7 %}">
                                        <img src="https://i.postimg.cc/tCsL1yM6/Dijes.jpg" alt="">
                                    </a>
                                    <h2 class="prod-i-ttl">Diges</h2>
                                </div>
                            </div>
                        </article>  
                        <article class="cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6 sectgl-item">
                            <div class="sectgl prod-i">
                                <div class="prod-i-top">
                                    <a class="prod-i-img" href="{% url 'web:categoria' 6 %}">
                                        <img src="https://i.postimg.cc/GmywfrPR/Gemelos.jpg" alt="">
                                    </a>
                                    <h2 class="prod-i-ttl">Gemelos</h2>
                                </div>
                            </div>
                        </article> 
                        <article class="cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6 sectgl-item">
                            <div class="sectgl prod-i">
                                <div class="prod-i-top">
                                    <a class="prod-i-img" href="{% url 'web:categoria' 6 %}">
                                        <img src="https://i.postimg.cc/qv8Dn7XN/Aretes.jpg" alt="">
                                    </a>
                                    <h2 class="prod-i-ttl">Aretes</h2>
                                </div>
                            </div>
                        </article>   
                        <article class="cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6 sectgl-item">
                            <div class="sectgl prod-i">
                                <div class="prod-i-top">
                                    <a class="prod-i-img" href="{% url 'web:categoria' 6 %}">
                                        <img src="https://i.postimg.cc/PxMfpT0S/oferta.jpg" alt="">
                                    </a>
                                    <h2 class="prod-i-ttl">Ofertas</h2>
                                </div>
                            </div>
                        </article>   
                    </div>
                    <p class="special-more">
                        <a class="special-more-btn" href="{% url 'web:galeria' %}">Mostrar Mas Productos</a>
                    </p>
                </div>
                <div class="page-styling row-wrap-full front-image-half">
                    <section class="image-half image-half-right">
                        <div class="image-half-img" style="background-image: url(../static/img/calidad.jpg);">
                            <img src="http://placehold.it/1006x498" alt="">
                        </div>
                        <div class="cont image-half-cont">
                            <div class="image-half-inner">
                                <h2>Calidad</h2>
                                <div class="wpb_text_column wpb_content_element ">
                                    <div class="wpb_wrapper">
                                        <p>
                                            Antes de que una pieza de joyería pueda llevar el nombre de Encanto
                                            Finos debe pasar una rigurosa serie de inspecciones. Usted
                                            tiene altos estándares, por lo que los nuestros son aún más altos.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
                <div class="page-styling row-wrap-full front-image-half">
                    <section class="image-half image-half-left">
                        <div class="image-half-img" style="background-image: url(../static/img/arte.png);">
                            <img src="http://placehold.it/1006x498" alt="">
                        </div>
                        <div class="cont image-half-cont">
                            <div class="image-half-inner">
                                <h2>ARTE</h2>
                                <p>
                                    Fabricamos todo tipo de joyas de oro personalizados según estándares de
                                    calidad exigentes y un gemólogo experto inspecciona todas las joyas de
                                    diamantes antes de que lleguen a usted.
                                </p>
                            </div>
                        </div>
                    </section>
                </div>
                </div>
            </main>
        </div>
    </div>

    <div class="modal-form" id="modal-form">
        <form action="{% url 'web:senddata' %}" method="POST" class="">
            {% csrf_token %}
            <h4>Contáctanos</h4>
            <input type="text" placeholder="Nombre" data-required="text" name="nombre">
            <input type="email" placeholder="Correo" data-required="text" data-required-email="email" name="email">
            <textarea placeholder="Mensaje" class="form-control" name="contenido" rows="10" required></textarea>
            <input class="btn1" type="submit" value="Enviar" >
        </form>
    </div>
    <script>
        function enviarMensaje() {
            alert('Mensaje enviado');
        }
    </script>
</div>
</div>
{% endblock %}

proyecto/web/templates/producto.html
{% extends 'layout.html' %}
{% block content %}
<div class="cont maincont">
    <article>
        <div class="prod">
            <div class="prod-slider-wrap prod-slider-shown">
                <div class="flexslider prod-slider" id="prod-slider">
                    <ul class="slides">
                        <li>
                            <a data-fancybox-group="prod" class="fancy-img" href="http://placehold.it/810x722">
                                <img src="{{producto.imagen.url}}" alt="">
                            </a>
                        </li>
                        <li>
                            <a data-fancybox-group="prod" class="fancy-img" href="http://placehold.it/800x800">
                                <img src="{{producto.imagen.url}}" alt="">
                            </a>
                        </li>
                    </ul>
                    <div class="prod-slider-count">
                        <p><span class="count-cur">1</span> / <span class="count-all">2</span></p>
                        <p class="hover-label prod-slider-zoom"><i class="icon ion-search"></i><span>Zoom In</span></p>
                    </div>
                </div>
                <div class="flexslider prod-thumbs" id="prod-thumbs">
                    <ul class="slides">
                        <li>
                            <img src="{{producto.imagen.url}}" alt="">
                        </li>
                        <li>
                            <img src="{{producto.imagen.url}}" alt="">
                        </li>
                    </ul>
                </div>
            </div>

            <div class="prod-cont">
                <form action="{% url 'web:carritoadd' producto.id %}" method="post">
                    {% csrf_token %}
                    <div class="prod-rating-wrap">
                        <p data-rating="4" class="prod-rating">
                            <i class="rating-ico" title="1"></i><i class="rating-ico" title="2"></i><i
                                class="rating-ico" title="3"></i><i class="rating-ico" title="4"></i><i
                                class="rating-ico" title="5"></i>
                        </p>
                        <p class="prod-rating-count">7</p>
                    </div>
                    <p class="prod-categs"><a href="#">{{producto.categoria.nombre}}</a>, <a
                            href="#">{{producto.marca.nombre}}</a></p>
                    <h1>{{producto.nombre}}</h1>
                    <div class="variations_form cart">
                        <p class="prod-price">${{producto.precio}}</p>
                        <div class="prod-add">
                            <button type="submit" class="button"><i class="icon ion-android-cart"></i> Agregar al
                                carrito</button>
                            <p class="qnt-wrap prod-li-qnt">
                                <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                <input type="text" name="cantidad" value="1">
                                <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                            </p>
                            <div class="prod-li-favorites">
                                <a href="#" class="hover-label add_to_wishlist"><i
                                        class="icon ion-heart"></i></a>
                            </div>
                            <p class="prod-li-compare">
                                <a href="#" class="hover-label prod-li-compare-btn"><i
                                        class="icon ion-arrow-swap"></i></a>
                            </p>
                        </div>
                    </div>

                    <div class="prod-props">
                        <dl class="product_meta">
                            <dt>SKU:</dt>
                            <dd>2135687</dd>
                            <dt>Marca</dt>
                            <dd>{{producto.marca}}</dd>
                            <dt>Peso</dt>
                            <dd>{{producto.peso}} gm</dd>
                            <dt>Dimensions</dt>
                            <dd>{{producto.dimensiones}} cm</dd>
                            <dt>Fabricante</dt>
                            <dd>{{producto.pais}}</dd>
                            <dt>Material</dt>
                            <dd>{{producto.get_material_display}}</dd>
                        </dl>
                    </div>
                </form>
            </div>

            <p class="prod-badge">
                <span class="badge-1">{{producto.get_sexo_display}}</span>
            </p>
        </div>
        <div class="prod-tabs-wrap">
            <ul class="prod-tabs">
                <li id="prod-desc" class="active" data-prodtab-num="1">
                    <a data-prodtab="#prod-tab-1" href="#">Description</a>
                </li>
            </ul>
            <div class="prod-tab-cont">
                <p data-prodtab-num="1" class="prod-tab-mob active" data-prodtab="#prod-tab-1">Description</p>
                <div class="prod-tab page-styling prod-tab-desc" id="prod-tab-1">
                    <p>
                        {{producto.descripcion}}
                    </p>
                </div>
            </div>
        </div>
    </article>
</div>

{% endblock %}

proyecto/web/templates/shop.html
{% extends 'layout.html' %}
{% block content %}
<div class="cont maincont">
    <div class="section-top">
        <h1 class="maincont-ttl">Tienda</h1>
    </div>
    <div class="section-wrap-withsb">
        <aside class="blog-sb-widgets section-sb" id="section-sb">
            <div class="theiaStickySidebar">
                <div class="section-filter">
                    <div class="section-filter">
                        <div class="blog-sb-widget multishopcategories_widget">
                            <h3 class="widgettitle">Categorias</h3>
                            <div class="section-sb-current">
                                <ul class="section-sb-list">
                                    {% for categoria in categorias %}
                                    <li>
                                        <a href="{% url 'web:categoria' categoria.id %}">
                                            <span class="section-sb-label">{{categoria.nombre}} 
                                        <span class="count">{{categoria.producto_set.all.count}}</span></span></a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                        <div class="blog-sb-widget multishopbrands_widget">
                            <h3 class="widgettitle">Marcas</h3>
                            <ul class="brands-list-sb">
                                {% for marca in marcas %}
                                <li>
                                    <a href="{% url 'web:marca' marca.id %}">{{marca.nombre}} 
                                        <span class="count">{{marca.producto_set.all.count}}</span></a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </aside>        
        <div class="section-list-withsb" id="section-list-withsb">
        <div class="theiaStickySidebar">
            <div class="row prod-items prod-items-2">
                {% for producto in productos %}
                <article class="cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6 sectgl-item">
                    <div class="sectgl prod-i">
                        <div class="prod-i-top">
                            <a class="prod-i-img" href="{% url 'web:producto' producto.id %}">
                                <img src="{{producto.imagen.url}}" alt="">
                            </a>
                        </div>
                        <div class="prod-i-bot">
                            <div class="prod-i-info">
                                <p class="prod-i-price">${{producto.precio}}</p>
                                <p class="prod-i-categ"><a href="catalog-gallery.html">{{producto.marca.nombre}}</a></p>
                            </div>
                            <h3 class="prod-i-ttl"><a href="{% url 'web:producto' producto.id %}">{{producto.nombre}}</a></h3>
                        </div>
                    </div>
                </article>
                {% endfor %}        
            </div>
            <ul class="page-numbers">
                <li><a class="page-numbers" href="{% url 'web:shop' 1 %}"><span class="page-numbers current">1</span></a></li>
                <li><a class="page-numbers" href="{% url 'web:shop' 2 %}">2</a></li>
                <li><a class="page-numbers" href="{% url 'web:shop' 3 %}">3</a></li>
                <li><a class="page-numbers" href="{% url 'web:shop' 4 %}">4</a></li>
                <li><a class="next page-numbers" href="#"><i class="fa fa-angle-right"></i></a></li>
            </ul>
        </div>
    </div>
    </div>

</div>
{% endblock %}

proyecto/web/templates/vercarrito.html
{% extends 'layout.html' %}
{% block content %}
<div class="cont maincont">
    <h1 class="maincont-ttl">Carrito</h1>
    <div class="page-styling">
        <div class="woocommerce prod-litems section-list">
            {% for producto in productos_carrito %}
            <article class="prod-li sectls">
                <div class="prod-li-inner">
                    <a href="product.html" class="prod-li-img">
                        <img src="{{producto.imagen}}" alt="">
                    </a>
                    <div class="prod-li-cont">
                        <div class="prod-li-ttl-wrap">
                            <p>
                                <a href="#">{{producto.categoria}}</a>
                            </p>
                            <h3><a href="product.html">{{producto.nombre}}</a></h3>
                        </div>
                        <div class="prod-li-prices">
                            <div class="prod-li-price-wrap">
                                <p>Price</p>
                                <p class="prod-li-price">${{producto.precio}}</p>
                            </div>
                            <div class="prod-li-qnt-wrap">
                                <p class="qnt-wrap prod-li-qnt">
                                    <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                    <input type="text" value="{{producto.cantidad}}" data-product-id="{{producto.producto_id}}">
                                    <a href="#" class="qnt-minus prod-li-minus"><i
                                            class="icon ion-arrow-down-b"></i></a>
                                </p>
                            </div>
                            <div class="prod-li-total-wrap">
                                <p>Subtotal</p>
                                <p class="prod-li-total">${{producto.subtotal}}</p>
                            </div>
                            <div class="prod-li-total-wrap">
                                <p class="prod-li-add">
                                    <a href="{% url 'web:carritodel' producto.producto_id %}"
                                        class="button hover-label prod-addbtn"><i class="icon ion-close-round"></i></a>
                                </p>
                            </div>
                        </div>
                    </div>

                </div>
            </article>
            {% endfor %}
        </div>
        <div class="cart-actions">
            <div class="coupon">
                <input type="text" placeholder="Coupon code">
                <input type="submit" class="button" producto="Apply">
            </div>
            <div class="cart-collaterals">
                <a href="{% url 'web:carritoclear' %}" class="checkout-button button">Limpiar carrito</a>
                <a href="{% url 'web:factura' %}" class="checkout-button button">Registar pedido</a>
                <div class="order-total">
                    <p class="cart-totals-ttl">Total</p>
                    <p class="cart-totals-val">{{total}}</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}